### PR TITLE
Corrected processing of reserved parameter <<resourcePathName>>

### PR DESCRIPTION
**Pull request by bpowell65536**
The [parameters](https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#parameters) section of the RAML 0.8 spec states that the ``<<resourcePathName>>`` reserved parameter should be populated with the section of the resource path after the right-most '/' character. Currently ``ramlfications`` populates the ``<<resourcePathName>>`` parameter with the section of the resource path after the _left-most_ '/' character. This change corrects this behaviour.

### CODE REVIEW

**Comment by econchick** [comment]
Question: is resourcePathName supposed to be the last bit of the path, (eg `/{id}`) or the "full" path (eg `/users/{id}`)?

**Comment by bpowell65536** [comment]
@econchick The RAML 0.8 spec says:

> In resource type definitions, there are two reserved parameter names: resourcePath and 
> resourcePathName. The processing application MUST set the values of these reserved 
> parameters to the inheriting resource's path (for example, "/users") and the part of the path 
> following the rightmost "/" (for example, "users"), respectively."

To answer your question: It looks like ``resourcePathName`` is supposed to be the last part of the path, but without any leading '/' character (i.e. ``path.split("/")[-1]``). The full path (including all the '/' characters) is provided as well, as the ``resourcePath`` parameter.

**Comment by econchick** [comment]
@bpowell65536 I did read that, but it's unclear in the spec's example if `/users` is a root-level defined resource or a child resource, if that makes sense.

**Comment by bpowell65536** [comment]
The example is ambiguous in that regard, but given that ``resourcePathName`` is 

> the part of the path following the rightmost "/"

does it matter if the resource is a root-level resource or a child resource? The example says "/users" resolves to "users", but wouldn't  "/root/users" also resolve to "users"?

**Comment by econchick** [comment]
Nope, you're right - I am just an idiot :D

**Comment by econchick** [comment]
Before I merge this, could you rebase on v0.2.0-dev to fix the merge conflicts?

**Comment by bpowell65536** [comment]
@econchick Great, I was hoping I hadn't really screwed up my reading of the spec there :P I'll rebase this from v0.2.0-dev now.

**Comment by econchick** [comment]
Thanks!

**Pull request merged**
