### PR TITLE
Added class NodeList

### PR DESCRIPTION
**Pull request by jmagnusson**
Allows for basic attribute filtering using filter_by method.
The user-facing API is inspired by the SQLAlchemy Query object.

This replaces PR #52.

### CODE REVIEW

**Comment by jmagnusson** [comment]
@econchick Any chance this could be merged? Don't want to do another round ;-)

**Comment by econchick** [comment]
Hey @jmagnusson ! Sorry for the delay!

You're patch is queued up to merge - I just need to figure out what I f*cked up when I was blindly merging a few days ago (lesson learned: don't merge via mobile!).

**Comment by econchick** [comment]
awesome - thank you!

**Comment by jmagnusson** [comment]
Awesome! Hope your merge issue was resolved. When can we expect a 0.2.0 release?

**Comment by jmagnusson** [comment]
@econchick Any chance we could have this backported? 😇

**Comment by econchick** [comment]
@jmagnusson reasonable request - if you'd like to make a PR against master, by all means. Otherwise it'll be prioritized after RAML 1.0 support (which I'm currently working on right now! literally! finally!)

**Comment by jmagnusson** [comment]
Wohoo! Maybe I can hold on a while longer then 😉

**Pull request merged**
