### PR TITLE
Fix for spotify#85

### PR DESCRIPTION
**Pull request by bpowell65536**

### CODE REVIEW

**Comment by bpowell65536** [comment]
If everything is OK with this PR, could it be merged into the v0.2.0-dev branch, please?

**Comment by econchick** [comment]
@bpowell65536 I am super busy this week and do not have time to review in the next day or two. Sorry!

**Comment by bpowell65536** [comment]
@econchick OK, thanks. Sorry for harassing you!

**Comment by econchick** [comment]
Sorry for the delay! Reviewed this on mobile - it looks okay so I'm hoping my merging doesn't break stuff! ☺️

**Comment by bpowell65536** [comment]
Thanks for reviewing this @econchick. I have done some testing of the updated v0.2.0-dev version against my original use case, and the fix seems to have worked. Do you want me to close this issue now?

**Pull request merged**
